

```{r}

# Load from other exp and rename immediatley
load(file = 'output/train_data_feat_dat.rda')

train_data_feat_dat <- train_data


load(file = 'output/test_data_feat_dat.rda')

test_data_feat_dat <- test_data

```



```{r}

dat <- readRDS('../../data/all_sim_m2m.rds')
# There is also m2a
  
dat <- dat$as_wide() %>% 
  select(-sim_opti3)

bn <- bestNormalize::bestNormalize(dat$sim_ratings)

hist(bn$x.t)

dat <- dat %>% 
  mutate(sim_ratings_norm = bn$x.t)
  
```


```{r}

# Fix the random numbers by setting the seed 
# This enables the analysis to be reproducible 
set.seed(123)

# Put 3/4 of the data into the training set 
data_split <- initial_split(dat, prop = 3/4)

# Create dataframes for the two sets:
train_data <- training(data_split) 
test_data <- testing(data_split)

```


```{r}

train_data <- train_data %>% 
  cbind(train_data_feat_dat %>% 
        select(-sim_ratings) %>% 
  rowwise() %>% 
  mutate(AvgIntervallicComplexity = mean(c_across(c(`Intervallic Complexity`, `Intervallic Complexity_2`))), 
         AvgBreadthofMaterial = mean(c_across(c(`Breadth of Material`, `Breadth of Material_2`))), 
         AvgTonality = mean(c_across(c(Tonality, Tonality_2))), 
         AvgDurationalComplexity = mean(c_across(c(`Durational Complexity`, `Durational Complexity_2`)))) %>% 
  ungroup())

```


```{r}

test_data <- test_data %>% 
  cbind(test_data_feat_dat %>% 
        select(-sim_ratings) %>% 
  rowwise() %>% 
  mutate(AvgIntervallicComplexity = mean(c_across(c(`Intervallic Complexity`, `Intervallic Complexity_2`))), 
         AvgBreadthofMaterial = mean(c_across(c(`Breadth of Material`, `Breadth of Material_2`))), 
         AvgTonality = mean(c_across(c(Tonality, Tonality_2))), 
         AvgDurationalComplexity = mean(c_across(c(`Durational Complexity`, `Durational Complexity_2`)))) %>% 
  ungroup())

```


```{r}


lm_1 <- lm(sim_ratings ~ sim_diffed + sim_harmcore + sim_ncdintioi + 
             sim_ngram_ioi_class_dist1 + sim_ngram_ioi_class_dist2 + 
             sim_ngrtvers + sim_ngrukko1 + sim_ngrukko2 + sim_ngrukkon + sim_rawed + sim_rhytfuzz, data = train_data)


lm_2 <- lm(sim_ratings_norm ~ sim_diffed + sim_harmcore + sim_ncdintioi + 
             sim_ngram_ioi_class_dist1 + sim_ngram_ioi_class_dist2 + 
             sim_ngrtvers + sim_ngrukko1 + sim_ngrukko2 + sim_ngrukkon + sim_rawed + sim_rhytfuzz, data = train_data)

lm_3 <- lm(sim_ratings ~ sim_diffed + sim_harmcore + sim_ncdintioi + 
             sim_ngram_ioi_class_dist1 + sim_ngram_ioi_class_dist2 + 
             sim_ngrtvers + sim_ngrukko1 + sim_ngrukko2 + sim_ngrukkon + sim_rawed + sim_rhytfuzz +
             AvgIntervallicComplexity + AvgBreadthofMaterial + AvgTonality + AvgDurationalComplexity, data = train_data)


```




```{r}


test_data <- test_data %>% 
  mutate(pred = predict(lm_1, newdata = test_data),
         pred2 = predict(lm_2, newdata = test_data),
         pred3 = predict(lm_3, newdata = test_data),
         )


```


```{r}

test_data %>% 
  ggplot(aes(x = pred3, y = sim_ratings)) +
    geom_point() +
    geom_smooth(
      method = "lm"
      ) +
    theme_minimal()

```


```{r}

lm_reg <- lm(sim_ratings ~ pred, data = test_data)

```

```{r}

summary(lm_reg)

```

```{r}

lm_reg2 <- lm(sim_ratings_norm ~ pred, data = test_data)

```

```{r}

summary(lm_reg2)

```


```{r}

Metrics::rmse(test_data$sim_ratings, test_data$pred)

Metrics::rmse(test_data$sim_ratings, test_data$pred2)


```


```{r}


bb_mod_dat <- 
  train_data %>% 
        mutate_if(is.numeric, ~ round(1000 * .x)) %>%
        mutate(sim_ratings_complement = 1000 - sim_ratings)


bb_mod <- 
  gamlss::gamlss(data = bb_mod_dat, 
                 formula = cbind(sim_ratings, sim_ratings_complement) ~ 1 + sim_diffed + sim_harmcore + sim_ncdintioi +
                  sim_ngram_ioi_class_dist1 + sim_ngram_ioi_class_dist2 +
                  sim_ngrtvers + sim_ngrukko1 + sim_ngrukko2 + sim_ngrukkon + 
                  sim_rawed + sim_rhytfuzz,
                family = gamlss.dist::BB(),
                control = gamlss::gamlss.control(trace = F, save = T))

```


```{r}


bb_mod_dat_test <- 
  test_data %>% 
        select(c(sim_ratings, sim_diffed, sim_harmcore, sim_ncdintioi,
                  sim_ngram_ioi_class_dist1, sim_ngram_ioi_class_dist2,
                  sim_ngrtvers, sim_ngrukko1,  sim_ngrukko2, sim_ngrukkon,
                  sim_rawed, sim_rhytfuzz)) %>% 
        mutate_if(is.numeric, ~ round(1000 * .x)) %>%
        mutate(sim_ratings_complement = 1000 - sim_ratings)

bb_mod_dat_test <- bb_mod_dat_test %>% 
  mutate(bb_pred = stats::predict(bb_mod, type = "response",
                     newdata = bb_mod_dat_test,
                     data = bb_mod_dat) * 1000)

```


```{r}

lm_reg3 <- lm(sim_ratings ~ bb_pred, data = bb_mod_dat_test)


summary(lm_reg3)

```


```{r}

Metrics::rmse(bb_mod_dat_test$sim_ratings, bb_mod_dat_test$bb_pred)/1000


```


```{r}

lm_reg4 <- lm(sim_ratings ~ pred3, data = test_data)


summary(lm_reg4)

```


```{r}

Metrics::rmse(test_data$sim_ratings, test_data$pred3)


```


```{r}

test_data <- test_data %>% 
  mutate(bb_pred = bb_mod_dat_test$bb_pred/1000) %>% 
  rowwise() %>% 
  mutate(ensemblepred = mean(c_across(c(pred, bb_pred, pred3)), na.rm = TRUE)) %>% 
  ungroup()

```



```{r}

Metrics::rmse(test_data$sim_ratings, test_data$ensemblepred)


```


```{r}

lm_reg4 <- lm(sim_ratings ~ ensemblepred, data = test_data)


summary(lm_reg4)

```



```{r}

save(test_data, file = 'output/lm_and_bb_test_data.rda')

```


