


```{r}

library(psych)

```

```{r}

dat_pca <- readRDS('../../data/all_sim_m2m.rds')
# There is also m2a
  
dat_pca <- dat_pca$as_wide()

```


```{r}

# Fix the random numbers by setting the seed 
# This enables the analysis to be reproducible 
set.seed(123)

# Put 3/4 of the data into the training set 
data_split <- initial_split(dat_pca, prop = 3/4)

# Create dataframes for the two sets:
train_data <- training(data_split) 
test_data <- testing(data_split)

```


```{r}

train_data %>% 
  select(sim_diffed:sim_rhytfuzz) %>% 
  select(-sim_opti3) %>% 
  fa.parallel()

```

```{r}

pca_mod1 <- train_data %>% 
  select(sim_diffed:sim_rhytfuzz) %>% 
  select(-sim_opti3) %>% 
  principal(nfactors = 2)

```


```{r}

print(pca_mod1)

```

```{r}

train_data <- train_data %>% 
  cbind(predict(pca_mod1, data = train_data %>% 
  select(sim_diffed:sim_rhytfuzz) %>% 
  select(-sim_opti3)
  ))

```


```{r}

lm_pca_reg <- lm(sim_ratings ~ RC1 + RC2, data = train_data)


```


```{r}

summary(lm_pca_reg)

```


```{r}

test_data <- test_data %>% 
  cbind(predict(pca_mod1, 
                     
                     old.data = train_data %>%
                       select(sim_diffed:sim_rhytfuzz) %>%
                       select(-sim_opti3),

                     data = test_data %>% 
                       select(sim_diffed:sim_rhytfuzz) %>% 
                       select(-sim_opti3)
                     
                     ) %>% tibble::as_tibble()
  ) %>% 
  mutate(pred = predict(lm_pca_reg, newdata = .))


```




```{r}

pca_reg <- lm(sim_ratings ~ pred, data = test_data)

```

```{r}

summary(pca_reg)

```


```{r}

test_data_pca <- test_data

```


```{r}

load(file = 'output/lm_and_bb_test_data.rda')


```


```{r}

test_data_pca <- cbind(test_data_pca,
                       test_data %>% select(pred, bb_pred) %>% rename(pred2 = pred) )

```



```{r}

test_data_pca <- test_data_pca %>% 
  rowwise() %>% 
  mutate(ensemblepred = mean(c_across(c(pred, pred2, bb_pred)), na.rm = TRUE)) %>% 
  ungroup()

```



```{r}

Metrics::rmse(test_data_pca$sim_ratings, test_data_pca$ensemblepred)


```


```{r}

ensemble_reg <- lm(sim_ratings ~ ensemblepred, data = test_data_pca)


summary(ensemble_reg)

```




